// Module2_FrontendDev/NISHANTHIKA.P/hands_on_7/components/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  siteName = 'Student Portal';
}

<header class="site-header">
  <div class="site-title">{{ siteName }}</div>
  <nav aria-label="Main navigation">
    <a
      routerLink="/"
      routerLinkActive="active-link"
      [routerLinkActiveOptions]="{ exact: true }"
    >
      Courses
    </a>
    <a routerLink="/profile" routerLinkActive="active-link">Profile</a>
  </nav>
</header>

// Module2_FrontendDev/NISHANTHIKA.P/hands_on_10/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";
import { selectEnrolledCount } from "../store/enrollmentSlice.js";

function Header() {
  const enrolledCount = useSelector(selectEnrolledCount);

  return (
    <header className="site-header">
      <div className="site-title">Student Portal</div>
      <nav aria-label="Main navigation">
        <Link to="/">Home</Link>
        <Link to="/courses">Courses</Link>
        <Link to="/profile">Profile</Link>
      </nav>
      <span className="enrolled-badge">Enrolled: {enrolledCount}</span>
    </header>
  );
}

export default Header;
