// Module2_FrontendDev/NISHANTHIKA.P/hands_on_7/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './components/header/header.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'student-portal-angular';
}

<app-header></app-header>

<main>
  <router-outlet></router-outlet>
</main>

<footer>
  <p>&copy; 2026 Student Portal. Digital Nurture 5.0.</p>
</footer>

// Module2_FrontendDev/NISHANTHIKA.P/hands_on_10/src/App.jsx
import { Routes, Route } from "react-router-dom";
import Header from "./components/Header.jsx";
import HomePage from "./pages/HomePage.jsx";
import CoursesPage from "./pages/CoursesPage.jsx";
import ProfilePage from "./pages/ProfilePage.jsx";

function App() {
  return (
    <>
      <Header />
      <main>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/courses" element={<CoursesPage />} />
          <Route path="/profile" element={<ProfilePage />} />
        </Routes>
      </main>
      <footer className="site-footer">
        <p>&copy; 2026 Student Portal. Digital Nurture 5.0.</p>
      </footer>
    </>
  );
}

export default App;
