// Module2_FrontendDev/NISHANTHIKA.P/hands_on_5/components/CourseCard.jsx
function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span>{credits} credits</span>
      {grade && <p className="grade">Grade: {grade}</p>}
      {onEnroll && (
        <button onClick={() => onEnroll({ id, name, code, credits, grade })}>
          Enroll
        </button>
      )}
    </article>
  );
}

export default CourseCard;

// Module2_FrontendDev/NISHANTHIKA.P/hands_on_7/components/course-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './course-card.component.html',
  styleUrl: './course-card.component.css',
})
export class CourseCardComponent {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}

<article class="course-card">
  <h3>{{ name }}</h3>
  <p>{{ code }}</p>
  <span>{{ credits }} credits</span>
  <p *ngIf="grade && grade !== '-'" class="grade">Grade: {{ grade }}</p>
</article>
