// Module2_FrontendDev/NISHANTHIKA.P/hands_on_6/components/Header.jsx
import { Link, useLocation } from "react-router-dom";
import { useSelector } from "react-redux";
import { selectEnrolledCount } from "../store/enrollmentSlice.js";

function Header({ siteName }) {
  const enrolledCount = useSelector(selectEnrolledCount);
  const location = useLocation();

  const links = [
    { to: "/", label: "Home" },
    { to: "/courses", label: "Courses" },
    { to: "/profile", label: "Profile" },
  ];

  return (
    <header className="site-header">
      <div className="site-title">{siteName}</div>
      <nav aria-label="Main navigation">
        <ul>
          {links.map((link) => (
            <li key={link.to}>
              <Link
                to={link.to}
                aria-current={location.pathname === link.to ? "page" : undefined}
              >
                {link.label}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <span className="enrolled-badge">Enrolled: {enrolledCount}</span>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/NISHANTHIKA.P/hands_on_7/components/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  siteName = 'Student Portal';
}

<header class="site-header">
  <div class="site-title">{{ siteName }}</div>
  <nav aria-label="Main navigation">
    <a
      routerLink="/"
      routerLinkActive="active-link"
      [routerLinkActiveOptions]="{ exact: true }"
    >
      Courses
    </a>
    <a routerLink="/profile" routerLinkActive="active-link">Profile</a>
  </nav>
</header>
